---

- when: "ansible_os_family == 'Debian'"
  import_vars: '{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version }}.yml'

- name: set time zone
  timezone:
    name: '{{ system_timezone }}'
  tags:
    - timezone

# -----------------------------------------------------------------------------
# get rid of chrony
# -----------------------------------------------------------------------------

- name: remove chrony
  package:
    pkg: chrony
    state: absent

# -----------------------------------------------------------------------------
# install ntp
# -----------------------------------------------------------------------------

- name: install ntp
  package:
    pkg: '{{ ntp_distro_packages | join(",") }}'

- name: stat distro ntp.conf
  stat:
    path: /etc/ntp.conf
  register: __ntp_conf_dest
  tags:
    - ntp-conf

- name: configure ntp
  template:
    src: '{{ lookup("first_found", __ntp_conf_templates) }}'
    dest: /etc/ntp.conf
    owner: '{{ __ntp_conf_dest.stat.pw_name }}'
    group: '{{ __ntp_conf_dest.stat.gr_name }}'
    mode: '{{ __ntp_conf_dest.stat.mode }}'
  register: __ntp_configuration
  tags:
    - ntp-conf

- name: enable ntpd service and assure it is started
  service:
    name: '{{ ntp_service_name }}'
    enabled: yes
    state: >-
      {{
        __ntp_configuration.changed |
          default(False) |
          ternary("restarted", "started")
      }}
  tags:
    - ntp-conf
    - ntp-service
    - service
    - service-ntp

...
